
export const industries = [

{ name : "E-commerce",
keywords: [
  "online shopping",
  "buy online",
  "shop online",
  "e-commerce",
  "online store",
  "retail",
  "shopping cart",
  "digital commerce",
  "internet shopping",
  "virtual storefront",
  "online marketplace",
  "web store",
  "electronic retail",
  "cybermall",
  "web shop",
  "e-tailer",
  "online shop",
  "internet retailing",
  "online storefront",
  "web marketplace",
  "online merchandising",
  "digital storefront",
]
},

{
  name: "Finance",
  keywords: [
  "banking",
  "finance",
  "financial services",
  "investments",
  "wealth management",
  "insurance",
  "loans",
  "mortgages",
  "credit cards",
  "financial planning",
  "stock market",
  "asset management",
  "retirement planning",
  "personal finance",
  "wealth advisory",
  "financial consultancy",
  "fiscal services",
  "investment banking",
  "financial products",
  "wealth accumulation",
  "portfolio management",
]
},
{
  name: "healthcare",
   keywords: [
  "healthcare",
  "medical",
  "hospitals",
  "clinics",
  "health services",
  "medical supplies",
  "pharmaceuticals",
  "healthcare providers",
  "medical equipment",
  "healthcare facilities",
  "healthcare technology",
  "healthcare solutions",
  "patient care",
  "healthcare professionals",
  "medical treatment",
  "healthcare delivery",
  "healthcare management",
  "healthcare systems",
  "healthcare industry",
  "medical services",
  "healthcare administration",
  "healthcare consulting",
  "Health Care",
  "Health",
  "diseases",
  "remedies",
   ]
  },

  {
  name: "technology",
  keywords: [
  "technology",
  "tech",
  "software",
  "hardware",
  "IT services",
  "innovation",
  "digital",
  "technology solutions",
  "tech products",
  "technology trends",
  "IT infrastructure",
  "software development",
  "tech industry",
  "technology consulting",
  "technological advancements",
  "digital solutions",
  "information technology",
  "tech innovations",
  "tech startups",
  "tech companies",
  "technology services",
]
  }
  ,
  {
  name: "education",
  keywords: [
  "education",
  "e-learning",
  "online courses",
  "schools",
  "universities",
  "training",
  "learning management system (LMS)",
  "educational resources",
  "distance learning",
  "educational technology",
  "academic programs",
  "educational services",
  "online learning",
  "educational content",
  "educational materials",
  "educational institutions",
  "learning platforms",
  "instructional design",
  "educational programs",
  "educational software",
]},

{
name: "Travel",
keywords: [
  "travel",
  "tourism",
  "vacations",
  "hotels",
  "flights",
  "resorts",
  "destinations",
  "travel agencies",
  "tour operators",
  "travel booking",
  "travel experiences",
  "vacation packages",
  "travel accommodations",
  "travel guides",
  "travel services",
  "travel industry",
  "travel destinations",
  "tourism industry",
  "travel planning",
  "travel management",
]},
{

name: "real estate",
keywords: [
  "real estate",
  "properties",
  "homes for sale",
  "apartments",
  "commercial property",
  "realty",
  "listings",
  "real estate agents",
  "property management",
  "real estate investment",
  "property listings",
  "real estate services",
  "real estate market",
  "residential property",
  "real estate transactions",
  "real estate development",
  "real estate sales",
  "property investment",
  "real estate consultancy",
  "real estate appraisal",
]

},{
name: "automotive",
keywords: [
  "automotive",
  "cars",
  "vehicles",
  "auto parts",
  "car dealerships",
  "automotive services",
  "car rentals",
  "vehicle maintenance",
  "automotive industry",
  "automobile sales",
  "automotive repair",
  "car accessories",
  "automotive technology",
  "vehicle leasing",
  "automotive engineering",
  "automotive design",
  "automotive manufacturing",
  "automotive solutions",
  "automotive products",
  "automotive aftermarket",
]}
,{
  name: "Food and Beverages",
   keywords: [
  "food",
  "beverages",
  "restaurants",
  "dining",
  "food delivery",
  "recipes",
  "grocery",
  "food services",
  "culinary",
  "food industry",
  "beverage industry",
  "restaurant services",
  "food products",
  "food preparation",
  "food technology",
  "food distribution",
  "food retail",
  "food manufacturing",
  "food safety",
  "food processing",
]},{
name: "Fashion",
keywords: [
  "fashion",
  "apparel",
  "clothing",
  "fashion accessories",
  "designer",
  "clothing brands",
  "fashion trends",
  "fashion industry",
  "apparel design",
  "fashion retail",
  "clothing stores",
  "fashion designers",
  "fashion styling",
  "fashion collections",
  "fashion brands",
  "fashion labels",
  "fashion market",
  "fashion products",
]
},

{
  name: "Entertainment",
  keywords: [
    "entertainment",
    "music",
    "movies",
    "television",
    "streaming",
    "cinema",
    "shows",
    "performances",
    "celebrities",
    "artists",
    "actors",
    "actresses",
    "musicians",
    "bands",
    "comedy",
    "drama",
    "pop culture",
    "entertainment industry",
    "entertainment news"
  ]
}
]

