export interface ScheduleTask {
  // id is auto-generated by Supabase
  user_id: string;
  url: string;
  frequency: string;
  next_scrape: string; // timestamp
  // created_at is auto-generated by Supabase
  // updated_at is auto-generated by Supabase
  // result_history will initially be empty
}

export interface SavedResult {
  // how to store the result of a scrape?
  // this is just a placeholder
  result: string;
}

export interface UpdateScheduleTask {
  id: string
  user_id: string;
  url: string;
  frequency: string;
  next_scrape: string; // timestamp
  updated_at: string; // timestamp
  result_history: SavedResult[];
}

export interface ScheduleTaskResponse {
  id: string
  user_id: string;
  url: string;
  frequency: string;
  next_scrape: string; // timestamp
  updated_at: string; // timestamp
  created_at: string; // timestamp
  result_history: SavedResult[];
}
  

