name: Deploy 

on:
  push:
    branches: [config/grafana-loki]

jobs:
  deploy:
    name: Deploy grafana and loki
    runs-on: ubuntu-latest
    steps:  
      - name: Upload logs to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "logs"
          target: ./
      - name: Upload docker compose and config files to the server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "loki-grafana-setup"
          target: ./

      - name: Run docker compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd wee
            docker compose up --build --detach --force-recreate
