name: E2E Tests

on:
  pull_request:
    branches: [master, development]
  push:
    branches: [master, development]

permissions:
  contents: read

jobs:
  run-cypress-e2e-tests:
    name: Cypress E2E Tests
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SRV_KEY }}
      NEXT_PUBLIC_SUPABASE_ANON_PUBLIC_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_SENTRY_DSN_LINK: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN_LINK }}
      NEXT_PUBLIC_SENTRY_ORG: ${{ secrets.NEXT_PUBLIC_SENTRY_ORG }}
      NEXT_PUBLIC_SENTRY_PROJECT: ${{ secrets.NEXT_PUBLIC_SENTRY_PROJECT }}
      NEXT_PUBLIC_TESTING_ENVIRONMENT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        run: |
          cd wee/frontend
          npm ci

      - name: Start application
        run: |
          cd wee/frontend
          npx nx dev frontend &
          npx wait-on http://localhost:3000

      - name: Run Cypress E2E tests
        run: |
          cd wee/e2e/frontend-e2e
          npx cypress run --config video=false
